# -*- coding: utf-8 -*-
"""vision.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VC-3w32cn7_WgBaMcSiypdQ8J1dkjZRI
"""
import pandas as pd
import numpy as np
import ipdb
import logging
import sys
def strategy(f1,f2,f3):
	data1 = pd.read_csv(f1)##change dir
	data2 = pd.read_csv(f2)##change dir
	data3 = pd.read_csv(f3)##change dir
	#stock
	data1.index=data1["Date"]
	data1.drop("Date", axis = 1)
	date=list(data1.index)[2:]
	s1=data1['Adj Close'][list(data1['Adj Close'].index)[0]]
	ss1=data1['Adj Close'][list(data1['Adj Close'].index)[0:40]]
	b1=data1['Adj Close'][list(data1['Adj Close'].index)[40]]
	bb1=data1['Adj Close'][list(data1['Adj Close'].index)[40:80]]
	s2=data1['Adj Close'][list(data1['Adj Close'].index)[80]]
	ss2=data1['Adj Close'][list(data1['Adj Close'].index)[80:120]]
	b2=data1['Adj Close'][list(data1['Adj Close'].index)[120]]
	bb2=data1['Adj Close'][list(data1['Adj Close'].index)[120:160]]
	s3=data1['Adj Close'][list(data1['Adj Close'].index)[160]]
	ss3=data1['Adj Close'][list(data1['Adj Close'].index)[160:200]]
	b3=data1['Adj Close'][list(data1['Adj Close'].index)[200]]
	bb3=data1['Adj Close'][list(data1['Adj Close'].index)[200:]]
	stock_i=np.array(data1['Adj Close'][list(data1['Adj Close'].index)[2:]])
	r1=s1-ss1
	r2=bb1-b1+r1[-1]
	r3=s2-ss2+r2[-1]
	r4=bb2-b2+r3[-1]
	r5=s3-ss3+r4[-1]
	r6=bb3-b3+r5[-1]
	fr = pd.concat([r1,r2,r3,r4,r5,r6],axis=0)
	stock=np.array(list(fr.iloc[:])[:-2])	

	#bond
	data2.index=data2["Effective date "]
	data22=data2.drop("Effective date ", axis = 1)[:]
	bond=np.array(list(data22["Unnamed: 1"][:-2]))
	s1=data22["Unnamed: 1"][list(data22["Unnamed: 1"].index)[0]]
	ss1=data22["Unnamed: 1"][list(data22["Unnamed: 1"].index)[0:40]]
	b1=data22["Unnamed: 1"][list(data22["Unnamed: 1"].index)[40]]
	bb1=data22["Unnamed: 1"][list(data22["Unnamed: 1"].index)[40:80]]
	s2=data22["Unnamed: 1"][list(data22["Unnamed: 1"].index)[80]]
	ss2=data22["Unnamed: 1"][list(data22["Unnamed: 1"].index)[80:120]]
	b2=data22["Unnamed: 1"][list(data22["Unnamed: 1"].index)[120]]
	bb2=data22["Unnamed: 1"][list(data22["Unnamed: 1"].index)[120:160]]
	s3=data22["Unnamed: 1"][list(data22["Unnamed: 1"].index)[160]]
	ss3=data22["Unnamed: 1"][list(data22["Unnamed: 1"].index)[160:200]]
	b3=data22["Unnamed: 1"][list(data22["Unnamed: 1"].index)[200]]
	bb3=data22["Unnamed: 1"][list(data22["Unnamed: 1"].index)[200:]]
	bond_i=np.array(data22["Unnamed: 1"][list(data22["Unnamed: 1"].index)[:-2]])
	r1=s1-ss1
	r2=bb1-b1+r1[-1]
	r3=s2-ss2+r2[-1]
	r4=bb2-b2+r3[-1]
	r5=s3-ss3+r4[-1]
	r6=bb3-b3+r5[-1]
	fr2 = pd.concat([r1,r2,r3,r4,r5,r6],axis=0)
	bond=np.array(list(fr2.iloc[:])[:])[:-2]
	#USD
	data3.index=data3["Date"]
	data33=data3.drop("Date", axis = 1)
	USD_i=np.array(list(data33["Adj Close"]))
	s1=data33['Adj Close'][list(data33['Adj Close'].index)[0]]
	ss1=data33['Adj Close'][list(data33['Adj Close'].index)[0:40]]
	b1=data33['Adj Close'][list(data33['Adj Close'].index)[40]]
	bb1=data33['Adj Close'][list(data33['Adj Close'].index)[40:80]]
	s2=data33['Adj Close'][list(data33['Adj Close'].index)[80]]
	ss2=data33['Adj Close'][list(data33['Adj Close'].index)[80:120]]
	b2=data33['Adj Close'][list(data33['Adj Close'].index)[120]]
	bb2=data33['Adj Close'][list(data33['Adj Close'].index)[120:160]]
	s3=data33['Adj Close'][list(data33['Adj Close'].index)[160]]
	ss3=data33['Adj Close'][list(data33['Adj Close'].index)[160:200]]
	b3=data33['Adj Close'][list(data33['Adj Close'].index)[200]]
	bb3=data33['Adj Close'][list(data33['Adj Close'].index)[200:]]
	r1=s1-ss1
	r2=bb1-b1+r1[-1]
	r3=s2-ss2+r2[-1]
	r4=bb2-b2+r3[-1]
	r5=s3-ss3+r4[-1]
	r6=bb3-b3+r5[-1]
	fr3 = pd.concat([r1,r2,r3,r4,r5,r6],axis=0)
	USD=np.array(list(fr3.iloc[:])[:])	
	return stock,bond,USD,stock_i,bond_i,USD_i,date